### ISSUE TITLE
🚀 Feature: Usage of `DisplayName` instead of default `entityRef`

### ISSUE THREAD

**Issue by gaelgoth** [procore-oss/backstage-plugin-announcements#126]
### 🔖 Feature description

"Since Backstage v20.0, the usage of "displayName": "Amelia Park" in the catalog is the default way to display a user entity, instead of using "entityRef": user:default/amelia.park.

![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/55390114/cc1dd025-51fe-41d0-b245-c2e91e1dbf9c)

### 🎤 Context

As implemented in Backstage catalog: If exists use `DisplayName` of user/group. Else display default entity name. Part with "By UserName" need to be adapted:

![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/55390114/6bf86963-c773-4734-a356-2f614c70ecb2)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
Useful refs - 
- https://backstage.io/docs/releases/v1.20.0
- https://github.com/backstage/backstage/pull/17474

**Comment by kurtaking** [comment]
This is now [unblocked](https://github.com/procore-oss/backstage-plugin-announcements/pull/139) 🎉
