### ISSUE TITLE
🐛 Bug Report: missing announcementsApiRef export

### ISSUE THREAD

**Issue by p4welo** [procore-oss/backstage-plugin-announcements#155]
### 📜 Description

In tests, we need to provide `announcementApiRef` into `TestApiProvider`, but it's not exported in the plugin.

### 👍 Expected behavior

The `backstage-plugin-announcements` should export `announcementApiRef` in the file: 
`plugins/announcements/src/index.ts`

### 👎 Actual Behavior with Screenshots

`announcementApiRef` is not exported in the plugin so unit tests are failing
<img width="1089" alt="image" src="https://github.com/procore-oss/backstage-plugin-announcements/assets/1152581/e627626b-4c4c-4b00-a0f1-82cb64424f8d">

### 👟 Reproduction steps

1. Use a `NewAnnouncementBanner` component in the component.
2. Write a unit test using `TestApiProvider` and provide APIs that are used in the component.
3. The test will fail due to missing `announcementApiRef`

### 📃 Provide the context for the Bug.

I need to provide `announcementApiRef` mock into my `TestApiProvider`

### 🖥️ Your Environment

OS:   Darwin 23.1.0 - darwin/x64
node: v18.16.0
yarn: 1.22.21
cli:  0.23.1 (installed)
backstage:  1.19.6

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7
  @backstage/backend-common                                        0.19.8
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6
  @backstage/backend-tasks                                         0.5.11
  @backstage/backend-test-utils                                    0.2.7
  @backstage/catalog-client                                        1.4.5
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5
  @backstage/cli                                                   0.23.1
  @backstage/config-loader                                         1.5.2
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.13.7
  @backstage/core-plugin-api                                       1.7.0
  @backstage/dev-utils                                             1.0.22
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0
  @backstage/plugin-bazaar-backend                                 0.3.4
  @backstage/plugin-bazaar                                         0.2.17
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-node                                   1.4.7
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.9, 0.7.10
  @backstage/plugin-permission-node                                0.7.17
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-node                                  1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by kurtaking** [comment]
Hey @p4welo, I'm catching up on things today after being out of town the past week. I'll be more than happy to review a PR if you want to get one started. Otherwise, I can add it to a list of TODOs.

**Comment by kurtaking** [comment]
There is a typo in this issue. The API ref is `announcementsApiRef` (plural) and not `announcementApiRef`. Although, I do prefer it without being pluralized.
