### ISSUE TITLE
The plugin is giving 404 error not found

### ISSUE THREAD

**Issue by thabrez538** [procore-oss/backstage-plugin-announcements#173]
### 📜 Description

I was previously using k-phoen plugin for announcements and now I have installed the procore-oss/backstage-plugin-announcements.I am getting 404 not found for the API.Can someone help me with this?

### 👍 Expected behavior

I should be able to see my announcements in my backstage homepage

### 👎 Actual Behavior with Screenshots

I am getting 404 not found at my announcents tab 

### 👟 Reproduction steps

Followed the steps given in the setup guide-https://github.com/procore-oss/backstage-plugin-announcements/blob/main/docs/setup.md

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kurtaking** [comment]
Well that's no fun. I don't have an immediate answer for why things wouldn't be working. 

What version of Backstage are you running?

**Comment by thabrez538** [comment]
> > Well that's no fun. I don't have an immediate answer for why things wouldn't be working.
> > What version of Backstage are you running?
> 
> I was previously using backstage 1.16.0 and now I am upgrading it it to 1.20.3.With the version 1.20.3 it is not working.

Issue is resolved.Thanks
