### ISSUE TITLE
🚀 Feature: Support TokenManager for Collator to allow authentication with secured backends

### ISSUE THREAD

**Issue by Roshick** [procore-oss/backstage-plugin-announcements#249]
### 🔖 Feature description

Most collators use Backstage's TokenManager to generate a token for requests against the backend.  Securing the backend as per https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md currently breaks the collator, adding "/announcements" to the exceptions of not secured paths is a workaround, albeit not a rather good now.

### 🎤 Context

Like other collators, the one provided in [search-backend-module-announcements](https://github.com/procore-oss/backstage-plugin-announcements/tree/main/plugins/search-backend-module-announcements) should get the TokenManager injected.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
I'm a bit limited with moving this week, but am happy to provide a review if you get a PR started @Roshick.

**Comment by Roshick** [comment]
Sure, I will take a look at it and probably create a pull request around the beginning of next week. 

Good luck with your move! :)

**Comment by Roshick** [comment]
@kurtaking seeing that authentication is going to be changed substantially in 1.24.0, I think the best course of action here is to wait for the final release for this change. What do you think?

**Comment by kurtaking** [comment]
> @kurtaking seeing that authentication is going to be changed substantially in 1.24.0, I think the best course of action here is to wait for the final release for this change. What do you think?

I read up on that yesterday with the v1.23 release. 

There will be migration guides if not having the existing auth manager is preventing you from accomplishing something. If it isn't, then waiting makes sense to me. 👍🏼

**Comment by Longji-Kang** [comment]
Good day, we are also trying to integrate the announcement plugin into search. I would just like to find out if there's been any news regarding this enhancement since 1.24 has been released.

**Comment by Roshick** [comment]
Hey, my bad, I didn't link the issue in my pull request, it's currently still a draft but close to being finished (only documentation for integration with the old backend system is missing): https://github.com/procore-oss/backstage-plugin-announcements/pull/269

**Comment by Roshick** [comment]
@kurtaking  Are you sure that the new versions released on npm contain the changes? 

I'm currently trying to enable authentication in our instance again and the search module fails to authorize (as before). If I try it via local linking of the current mainline it works fine. Looking into the minified version of the dependencies, they don't seem to contain the expected code (@procore-oss/backstage-plugin-search-backend-module-announcements 0.2.0 for example).

**Comment by Longji-Kang** [comment]
> @kurtaking Are you sure that the new versions released on npm contain the changes?
> 
> I'm currently trying to enable authentication in our instance again and the search module fails to authorize (as before). If I try it via local linking of the current mainline it works fine. Looking into the minified version of the dependencies, they don't seem to contain the expected code (@procore-oss/backstage-plugin-search-backend-module-announcements 0.2.0 for example).

Hi Roshick, how did you do the local linking with the current mainline?

**Comment by Roshick** [comment]
Hi @Longji-Kang, does this help? https://github.com/procore-oss/backstage-plugin-announcements/pull/269#issuecomment-2016882780

**Comment by Longji-Kang** [comment]
> Hi @Longji-Kang, does this help? [#269 (comment)](https://github.com/procore-oss/backstage-plugin-announcements/pull/269#issuecomment-2016882780)

Yep definitely. Just to clarify, you basically download the source code and then link it in the backstage project as shown in that link right?

**Comment by kurtaking** [comment]
> @kurtaking  Are you sure that the new versions released on npm contain the changes? 
> 
> 
> 
> I'm currently trying to enable authentication in our instance again and the search module fails to authorize (as before). If I try it via local linking of the current mainline it works fine. Looking into the minified version of the dependencies, they don't seem to contain the expected code (@procore-oss/backstage-plugin-search-backend-module-announcements 0.2.0 for example).

@Roshick I will check on this later today.

**Comment by Roshick** [comment]
Hey @kurtaking, any news on this?

**Comment by kurtaking** [comment]
> Hey @kurtaking, any news on this?

I looked on Sunday and was unable to figure out what was going on. The code is on `main` and the release is live on `npm` 😞. 

Any thoughts on what I should try next?

**Comment by Roshick** [comment]
> > Hey @kurtaking, any news on this?
> 
> I looked on Sunday and was unable to figure out what was going on. The code is on `main` and the release is live on `npm` 😞.
> 
> Any thoughts on what I should try next?

What's odd, if you take a look at the CHANGELOG.md here https://www.npmjs.com/package/@procore-oss/backstage-plugin-search-backend-module-announcements?activeTab=code it contains my change, but looking at the actual bundled code in dist/index.cjs.js (unfortunately the npmjs page doesn't seem to support direct links?!) and have a look at the "execute" method, it does not contain https://github.com/procore-oss/backstage-plugin-announcements/blob/main/plugins/search-backend-module-announcements/src/collators/AnnouncementCollatorFactory.ts#L49-L54.

It looks like something got messed up while building the distribution files and the old stuff was built. Maybe creating another release might fix this? Not sure how your release pipeline is set up...

**Comment by kurtaking** [comment]
> > > Hey @kurtaking, any news on this?
> > 
> > 
> > I looked on Sunday and was unable to figure out what was going on. The code is on `main` and the release is live on `npm` 😞.
> > Any thoughts on what I should try next?
> 
> What's odd, if you take a look at the CHANGELOG.md here https://www.npmjs.com/package/@procore-oss/backstage-plugin-search-backend-module-announcements?activeTab=code it contains my change, but looking at the actual bundled code in dist/index.cjs.js (unfortunately the npmjs page doesn't seem to support direct links?!) and have a look at the "execute" method, it does not contain https://github.com/procore-oss/backstage-plugin-announcements/blob/main/plugins/search-backend-module-announcements/src/collators/AnnouncementCollatorFactory.ts#L49-L54.
> 
> It looks like something got messed up while building the distribution files and the old stuff was built. Maybe creating another release might fix this? Not sure how your release pipeline is set up...

There will be a new release going out today with backstage updates that'll bump the package.

**Comment by Roshick** [comment]
Awesome, let's hope that fixes the problem! :)

Comparing the two versions shows that the dist files are indeed identical: https://www.npmjs.com/package/@procore-oss/backstage-plugin-search-backend-module-announcements/v/0.1.2?activeTab=code and https://www.npmjs.com/package/@procore-oss/backstage-plugin-search-backend-module-announcements?activeTab=code, maybe something to look into.

**Comment by kurtaking** [comment]
@Roshick, can you try `v0.2.1` and lemme know how things go.
