### ISSUE TITLE
🚀 Feature: Announcement "moderators"

### ISSUE THREAD

**Issue by msweaver** [procore-oss/backstage-plugin-announcements#257]
### 🔖 Feature description

We should be able to configure a group or subset of users who are allowed to make, edit, and delete announcements

### 🎤 Context

I have a group of people who are administrating our dev portal and I would like to limit normal user's ability to create/update/delete announcements

### ✌️ Possible Implementation

I would need to get more familiar with the implementation before trying to make changes to it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by msweaver** [comment]
I looked at the code for a minute and it seems like there is an implementation that connects to a backstage permission plugin, but that plugin doesn't appear to be well documented. I'll keep searching, maybe this feature exists and just needs to be documented how to use it?

**Comment by kurtaking** [comment]
> I looked at the code for a minute and it seems like there is an implementation that connects to a backstage permission plugin, but that plugin doesn't appear to be well documented. I'll keep searching, maybe this feature exists and just needs to be documented how to use it?

Hey @msweaver, permissions exist for each of those actions, so what you are looking for exists. 

It'll require you to have the [permissions framework](https://backstage.io/docs/permissions/getting-started) for Backstage enabled. 

You would then import and wire up the announcement permissions exported from the common package.

**Comment by msweaver** [comment]
Thanks for the guidance, I was able to get this working using the backstage permission framework.  I just wanted a mods group to be able to create/edit/delete:
```
  async handle(request: PolicyQuery, user?: BackstageIdentityResponse): Promise<PolicyDecision> {
    if ((request.permission.name === 'announcement.entity.delete' ||
      request.permission.name === 'announcement.entity.create' ||
      request.permission.name === 'announcement.entity.update')
      && user?.identity.ownershipEntityRefs.includes("group:default/dev-portal-mods")) {
      return {
        result: AuthorizeResult.ALLOW,
      };
    }
    return { result: AuthorizeResult.DENY };
  }
```

although now that I read it.. I'm going to refactor to reference you permission objects.
