### ISSUE TITLE
🚀 Feature: Extensible category hierarchy with Permission Control

### ISSUE THREAD

**Issue by sharadpattanshetti** [procore-oss/backstage-plugin-announcements#264]
### 🔖 Feature description

We would like to have hierarchy of categories created like multiple levels due to Organizational needs. The plugin should allow create sub categories and so on. It should also allow permission control so that only super admins kind of users of platform can control it. 

### 🎤 Context

The use case requirement is to have multiple level of categories defined. 
This would help end users go and refer respective announcements related to their personas and actions. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by kurtaking** [comment]
The announcement plugins have been migrated to [backstage/community-plugins](https://github.com/backstage/community-plugins) repo. Please recreate an issue there if there is value in doing so.
