### ISSUE TITLE
🚀 Feature: Better support for images

### ISSUE THREAD

**Issue by msweaver** [procore-oss/backstage-plugin-announcements#268]
### 🔖 Feature description

I would love to see some additional support around images. Currently it seems that you can link to an existing image, but I would love to see the ability to copy/paste an image into an announcement and have the plugin save/serve it. 

### 🎤 Context

My backstage implementation also uses the qeta plugin which supports this feature: https://github.com/drodil/backstage-plugin-qeta. 

### ✌️ Possible Implementation

I would probably start by seeing if this solution could be reused or easily ported: https://github.com/drodil/backstage-plugin-qeta/blob/40560c1dbbf3258cc867bd67b07cb1daf0a0a7ab/plugins/qeta/src/components/MarkdownEditor/MarkdownEditor.tsx#L32

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kurtaking** [comment]
@msweaver - do you find this to still be an issue?

**Comment by kunickiaj** [comment]
Def would like better support for images. Have been using github gists but recently realized they require logged in (to github) users to display. Its been a pain to host images separately from the announcement.

**Comment by kurtaking** [comment]
We've migrated the plugins. I have opened a copy of this issue in the community repo - https://github.com/backstage/community-plugins/issues/2414. 

I do not have time to contribute this, but hopefully migrating to the community repo makes it a bit easier for others to contribute.
