### ISSUE TITLE
🚀 Feature: Improve readability in AnnouncementBanner

### ISSUE THREAD

**Issue by ivangonzalezacuna** [procore-oss/backstage-plugin-announcements#275]
### 🔖 Feature description

We are using the announcements plugin for a while. Some of our developer have suggested that the banner colors are not the best regarding readability, specially in the light mode. We've seen this PR in the past: https://github.com/K-Phoen/backstage-plugin-announcements/pull/154, but it wasn't merged there, and doesn't seem to be here either. Is this something that would make sense?

### 🎤 Context

Some of our developer have complained about some readability issues in the banners, specially in the light theme. 

### ✌️ Possible Implementation

As mentioned above, a solution like the one described in https://github.com/K-Phoen/backstage-plugin-announcements/pull/154 could be a nice one.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kurtaking** [comment]
hey @ivangonzalezacuna, thanks for reaching out. I [posted on that issue](https://github.com/K-Phoen/backstage-plugin-announcements/pull/154#issuecomment-1792715436) in the past.

Happy to review a PR if you would like to contribute the functionality.

**Comment by kurtaking** [comment]
Maybe that is something @sravanireddy115 can help with?

**Comment by ivangonzalezacuna** [comment]
> hey @ivangonzalezacuna, thanks for reaching out. I https://github.com/K-Phoen/backstage-plugin-announcements/pull/154#issuecomment-1792715436 in the past.
> Happy to review a PR if you would like to contribute the functionality.

Hi! Unfortunately I don't have much time to try that out at the moment, so it would be nice if somebody else has some time to check this out. I guess some of the work can be easily done by the suggestion in that issue, but I'm not entirely sure.

**Comment by jmezach** [comment]
Just a thought here, but would it make sense to replace the banner entirely in favour of the new [Notifications support](https://backstage.io/docs/notifications/) in Backstage itself?

**Comment by kurtaking** [comment]
> Just a thought here, but would it make sense to replace the banner entirely in favour of the new [Notifications support](https://backstage.io/docs/notifications/) in Backstage itself?

@jmezach, its very likely the notifications plugin could replace announcements altogether.

**Comment by kurtaking** [comment]
The announcement plugins have been migrated to [backstage/community-plugins](https://github.com/backstage/community-plugins) repo. Please recreate an issue there if there is value in doing so.
