### ISSUE TITLE
🚀 Feature: Migrate to Material UI 5

### ISSUE THREAD

**Issue by Roshick** [procore-oss/backstage-plugin-announcements#281]
### 🔖 Feature description

Migrate to Material UI 5

### 🎤 Context

Backstage is moving towards full Material UI 5 and I think it would be a good idea for this plugin to also migrate to get rid of Material UI 4 dependencies altogether.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
Hey @Roshick, thanks for getting involved. I'd love to see this completed!

**Comment by Roshick** [comment]
@kurtaking I just had a look at this and most of the migration is done, but there appears to be some weird behavior between the snackbar and the backstage alerts api.

Looking at the documentation of the snackbar (https://mui.com/material-ui/react-snackbar/#usage), this element is not really made for in-flow placement anyway and I would suggest switching to alerts (https://mui.com/material-ui/react-alert/).

examples with alerts (different variants, text colors could be changed):
![variant1](https://github.com/procore-oss/backstage-plugin-announcements/assets/54182601/7b2a44c3-c752-4211-bb64-0c617ba2c9f1)
![variant2](https://github.com/procore-oss/backstage-plugin-announcements/assets/54182601/127a34db-0bd4-418e-84b0-724e86601773)
![variant3](https://github.com/procore-oss/backstage-plugin-announcements/assets/54182601/5c105d16-3079-41db-b484-0aa7e4dc49eb)

now the banner has some variant prop that can be either "block" and "floating", which I assume should toggle between in-flow and overlay, but I'm not quite sure... is the floating variant used anywhere?

**Comment by kurtaking** [comment]
Hey @Roshick, started work on this in https://github.com/procore-oss/backstage-plugin-announcements/pull/455. Do you want to give it a review? 

As far as the announcement banner goes, I agree that we need to move away from the Snackbar. I'll think through that on a separate PR.
