### ISSUE TITLE
🚀 Feature: Scaffolder Action

### ISSUE THREAD

**Issue by billabongrob** [procore-oss/backstage-plugin-announcements#293]
### 🔖 Feature description

It would be pretty cool to have a Scaffolder action that would add announcements so that we can use templates to provide a consistent look and feel to the announcements.  

### 🎤 Context

In my use case, we'd be using the AnnouncementPage along with the Components to make a specific route that shows just training opportunities.  In this case we might want to include things such a venue (on-site, remote, virtual), Cost, Description, or even pre-requisites.  I think this would allow us to extend the announcements plugin further and give users more flexibility on how it's used.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by kurtaking** [comment]
The announcement plugins have been migrated to [backstage/community-plugins](https://github.com/backstage/community-plugins) repo. Please recreate an issue there if there is value in doing so.
