### ISSUE TITLE
🚀 Feature: Ability to set a replacement for "Announcement" button in AnnouncementsPage Props

### ISSUE THREAD

**Issue by billabongrob** [procore-oss/backstage-plugin-announcements#298]
### 🔖 Feature description

The plugin currently allows for the customization of the title, subtitle and categories on AnnouncementsPageProps.  
It would be nice if we can modify what the button would say.  

### 🎤 Context

In our case, we're using multiple routes to serve certain announcements - for instance - "Training", "Team Lunch" etc... 
Currently, button says "New Announcement" - but it would be cool to override this with New - `$thing`.  Would probably look to the Categories for inspiration, but even then things may not align.  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
Hey @billabongrob, this change is fine, but it has me thinking. The functionality missing here is the ability to manage and create announcements from _any_ page of your choice. Therefore, it sounds like you are importing many versions of the `<AnnouncementsPage />`, overwriting the button name, and doing some filtering. Does that sound right?

If so, this seems like a stopgap when we should decouple announcements so you can create and display them anywhere.

**Comment by billabongrob** [comment]
Right now, I've created routes for each.  I've used the `<AnnouncementsPage />` within them.  Then just added them as a Nav bars on the side.  Here's an example of what my use case looks like.  
![Screenshot 2024-04-26 at 10 02 27 AM](https://github.com/procore-oss/backstage-plugin-announcements/assets/8441943/1d7b7764-f7e8-41ca-a62d-9922b3879950)

**Comment by kurtaking** [comment]
> Right now, I've created routes for each. I've used the `<AnnouncementsPage />` within them. Then just added them as a Nav bars on the side. Here's an example of what my use case looks like. ![Screenshot 2024-04-26 at 10 02 27 AM](https://private-user-images.githubusercontent.com/8441943/326039713-1d7b7764-f7e8-41ca-a62d-9922b3879950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTU4MjAsIm5iZiI6MTcxNDM1NTUyMCwicGF0aCI6Ii84NDQxOTQzLzMyNjAzOTcxMy0xZDdiNzc2NC1mN2U4LTQxY2EtYTYyZC05OTIyYjM4Nzk5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDE1MjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUzYmU5ZTk5YmYzMTc4MTRlZWJkNGVmNzA4NTA3YWMwMjNjNDEwOTljMzkzZGYxMTVkMWQ3MGY0Y2E4ZmQ4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jgTqpbZfvNOuStPHfZWYW9EmC7hudf68nxLSwzrAl6Q)

This is an interesting use of the plugins. My one concern is that you will continue to need to override to fit your unique use case. 

My approach for this would be to create some training plugin (`plugin-training`) where different options (`plugin-training-module-*`)s need to show announcements based on a category. Use the `AnnouncementsApi.announcements` from `announcements-react` to get the announcements for said training module. You would then supply your own `<Button />` that is wired up to `AnnouncementsApi.createAnnouncement`.

Or, make it slightly easier and we could provide additional components such as `<AnnouncementsGrid />` and/or `<AnnouncementsList />`.

**Comment by kurtaking** [comment]
@billabongrob are we good to close this?

**Comment by billabongrob** [comment]
All good @kurtaking 
Thanks!
