### ISSUE TITLE
🚀 Feature: Feedback Mechanism

### ISSUE THREAD

**Issue by billabongrob** [procore-oss/backstage-plugin-announcements#300]
### 🔖 Feature description

To enhance user engagement and gather valuable insights, it would be beneficial to introduce a user feedback tracking system. This system would enable users to express their opinions on announcements through likes and dislikes, providing administrators with valuable feedback on the effectiveness and relevance of their communications.

### 🎤 Context

In my use case, it's possible for announcements to become stale or for an announcement to provide no value.  While we strive to restrict who can post Announcements, it limits community engagement, so it would be valuable to allow the community to what is valuable so that we can remove the bad and promote the good.  

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by billabongrob** [comment]
I just realized that there was a discussion going on for this feature in #280 
Unsure whether this should be closed and moved into that discussion or how you'd like to proceed @kurtaking

**Comment by kurtaking** [comment]
> I just realized that there was a discussion going on for this feature in #280 
> 
> Unsure whether this should be closed and moved into that discussion or how you'd like to proceed @kurtaking 

Hey @billabongrob, I think we should pull @Roshick into the conversation here. It'll be nice to have a feature request associated with the change and it looks like you are willing to submit the PR.

@Roshick did you make any headway on this?

**Comment by Roshick** [comment]
Hey, I haven't started anything yet so go ahead! :)

**Comment by kurtaking** [comment]
The announcement plugins have been migrated to [backstage/community-plugins](https://github.com/backstage/community-plugins) repo. Please recreate an issue there if there is value in doing so.
