### ISSUE TITLE
🚀 Feature: Set or modify announcements dates

### ISSUE THREAD

**Issue by gaelgoth** [procore-oss/backstage-plugin-announcements#301]
### 🔖 Feature description

Add Announcements date edition

### 🎤 Context

Since the timeline (https://github.com/procore-oss/backstage-plugin-announcements/issues/119) has been introduced, announcements can be related to an event in the future. On announcement creation or edition users can set a date.

### ✌️ Possible Implementation

- ~Add a new column `announcement_event_date` in `announcements` table~
- ~Add a announcement event date field in create and edit announcement forms~
- ~Set  existing `created_at` as default value for announcement event date~

```
{
  startTime: Date;
  endTime: Date;
  active: boolean;
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

---
Edit:
- 2024.07.17: Replace Possible Implementation by kurtaking suggestion

**Comment by billabongrob** [comment]
I like this idea. One use case we have is using this plugin to announce events and events are generally time bound so this would be helpful to my team. 👍

**Comment by ShauliSolomovich** [comment]
I also like this idea 👍 , I think we can also benefit from a "Calendar" view.
Also for our use case to give announcements a "time frame"

**Comment by kurtaking** [comment]
What do you think about adding something like the below and setting `active` to false if it doesn't fall within the range? Thinking about how we could solve for this [issue](https://github.com/procore-oss/backstage-plugin-announcements/issues/379) as well in one go. 

```ts
{
  startTime: Date;
  endTime: Date;
  active: boolean;
}

**Comment by gaelgoth** [comment]
> What do you think about adding something like the below and setting `active` to false if it doesn't fall within the range? Thinking about how we could solve for this [issue](https://github.com/procore-oss/backstage-plugin-announcements/issues/379) as well in one go.
> 
> ```ts
> {
>   startTime: Date;
>   endTime: Date;
>   active: boolean;
> }
> ```

Good idea, I've been busy lately. I should be able to free up some time next month, but if anyone wants to get started please feel free to do so 😃

**Comment by yoramshai** [comment]
Hey @gaelgoth , do you think it will be implemented soon ?
Also I think it would be great to have date+time instead of s/m/M/y ago.

**Comment by gaelgoth** [comment]
@yoramshai I'm still busy on my side and  I've put this on hold due to the migration to the Backstage community repository (https://github.com/procore-oss/backstage-plugin-announcements/issues/373). If you're interested in taking this on, I'd be happy to assist you! 😊

**Comment by kurtaking** [comment]
The plugins have been migrated to the community repo.

**Comment by kurtaking** [comment]
@gaelgoth - can you create a copy of this issue in https://github.com/backstage/community-plugins? I am going to close it out here.
