### ISSUE TITLE
New versions released on npm do not contain the latest changes

### ISSUE THREAD

**Issue by kurtaking** [procore-oss/backstage-plugin-announcements#309]
@kurtaking  Are you sure that the new versions released on npm contain the changes? 

I'm currently trying to enable authentication in our instance again and the search module fails to authorize (as before). If I try it via local linking of the current mainline it works fine. Looking into the minified version of the dependencies, they don't seem to contain the expected code (@procore-oss/backstage-plugin-search-backend-module-announcements 0.2.0 for example).

_Originally posted by @Roshick in https://github.com/procore-oss/backstage-plugin-announcements/issues/249#issuecomment-2072054879_

**Comment by Roshick** [comment]
@kurtaking the latest release now includes my changes and the auth is working! :) It's probably still a good idea to try to understand how this happened.

**Comment by billabongrob** [comment]
This is pretty strange.  Noticed the same trying to run these in my environment:  
```
        <AnnouncementsPage
          ...
          buttonOptions={{ name: "Pizza" }}
          ...
          />
```
But am met with `Property 'buttonOptions' does not exist on type 'IntrinsicAttributes & { themeId?: string | undefined; title?: string | undefined; subtitle?: string | undefined; category?: string | undefined; cardOptions?: { ...; } | undefined; }'`
Running in: 
```
"@procore-oss/backstage-plugin-announcements@^0.6.2":
  version "0.6.2"
```
But the release says it's there...?  
https://github.com/procore-oss/backstage-plugin-announcements/blob/main/plugins/announcements/CHANGELOG.md#patch-changes

**Comment by kurtaking** [comment]
Weird. I don't know what is happening right now, and I am tapped out for resources. 😞

**Comment by kurtaking** [comment]
I tried reverting back to publishing with `yarn changset publish`, but that released two versions with the `workspace:^` in the package.json instead of the actual version. I'm still stumped on this.
