### ISSUE TITLE
🚀 Feature: Dynamically Adding Categories

### ISSUE THREAD

**Issue by billabongrob** [procore-oss/backstage-plugin-announcements#314]
### 🔖 Feature description

Currently, the new category area is not surfaced in the most user friendly manner.  ref: #310 
@JD-Gonz recommended the method similar to that which QETA uses today.  

### 🎤 Context

Primarily for user experience and not having to rework announcements when you realize the category you'd like to post in doesn't exist yet.  

### ✌️ Possible Implementation

![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/8441943/29b4bd31-6b99-4d25-af86-4b4ca2ed5814)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by JD-Gonz** [comment]
Thanks for opening this! I am pretty swamped with the day job at the moment but happy to collaborate and contribute where possible.

**Comment by kurtaking** [comment]
Take a look at https://github.com/procore-oss/backstage-plugin-announcements/pull/326. Feel free to leave a review 😄
