### ISSUE TITLE
🚀 Feature: Pre-populate announcements on load of the app

### ISSUE THREAD

**Issue by gayatrisamant18** [procore-oss/backstage-plugin-announcements#342]
### 🔖 Feature description

please share the steps to pre-populate announcements

### 🎤 Context

In my use-case i want to show the announcements of latest release post the backstage deployment

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kurtaking** [comment]
Hey @gayatrisamant18, I'm not entirely sure what you are asking. Announcements cannot be prepopulated from an external source if that's what you are asking.
