### ISSUE TITLE
🐛 Bug Report: Creating a category with a different slug and title will prevent the announcement from being created

### ISSUE THREAD

**Issue by rumiha** [procore-oss/backstage-plugin-announcements#351]
### 📜 Description

Creating a category with a different slug and title will prevent an announcement from being created with that category selected. Attempting to create a new announcement with such a category will throw the following error:
`backstage error Filtered internal error with logId=a4056554bf2c3b3194dc from response insert into "categories" ("slug", "title") values ($1, $2) - duplicate key value violates unique constraint "categories_pkey"`

The problem is in `CreateAnnouncementPage.tsx`, inside the `onSubmit` method. Function `slugs.indexOf(category)` will return -1 if the category slug and title are not the same, because it tries to find the category title inside an array of category slugs.

For example, when creating a new announcement, if the user selects the category `Test Category` and presses the submit button, it will throw an error. This happens because `Test Category` will not be found with `slugs.indexOf(category)` since the slug is `test-category`.

### 👍 Expected behavior

The code should use the slug from the selected category (not the title) to successfully search the slug array.

### 👎 Actual Behavior with Screenshots

1. Created new category
![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/56435838/ff2867a6-e7b2-4118-97a6-355f76cdfc1d)

2. Category created, but slug is different from title
![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/56435838/04465a4d-94a1-48b2-abf5-5f583ccab03b)

3. Creating new announcement and selecting created category
![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/56435838/08afe4c3-5b5e-4f3d-ac4c-6c30c4cdf72b)

4. Clicking submit button and getting error
![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/56435838/47196179-588f-45e9-8bc4-ca52e7aa8f40)

### 👟 Reproduction steps

1. Created new category
2. Category created, but slug is different from title
3. Creating new announcement and selecting created category
4. Clicking submit button and getting error

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by lavanya-sainik-ericsson** [comment]
Hey All, 

We would like to provide a fix for this bug and contribute in this plugin. Will share the PR soon for review.

**Comment by kurtaking** [comment]
@lavanya-sainik-ericsson @rumiha - 

@lavanya-sainik-ericsson's fix for this is in the latest release.
