### ISSUE TITLE
🚀 Feature: Able to delete Announcement Categories

### ISSUE THREAD

**Issue by lavanya-sainik-ericsson** [procore-oss/backstage-plugin-announcements#366]
### 🔖 Feature description

This feature request is to support deletion of Announcement Categories for following benefits:-

- If created by mistake, a user can delete that
- Categories doesn't get cluttered

### 🎤 Context

In this use case, when a user deletes an Announcement Category, then it deletes the category from the database and all the announcements with that category will have no announcement category. 

From UI perspective, there will be an option in the widget to delete the category

### ✌️ Possible Implementation

We would like to submit a PR for this feature

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by lavanya-sainik-ericsson** [comment]
Raised PR https://github.com/procore-oss/backstage-plugin-announcements/pull/367. Request your review and feedback

**Comment by kurtaking** [comment]
Completed in https://github.com/procore-oss/backstage-plugin-announcements/pull/367
