### ISSUE TITLE
Migrating announcements plugins to `@backstage-community/plugins` repository

### ISSUE THREAD

**Issue by kurtaking** [procore-oss/backstage-plugin-announcements#373]
# Summary

The announcement plugins should be migrated to [backstage/community-plugins](https://github.com/backstage/community-plugins). When we first took these over, that repository didn't exist, and the main repo no longer allowed new plugins. If it had, I would have migrated them there and volunteered to be a maintainer. The biggest benefit from migrating is the chance for additional maintainers passionate about the plugins to have more ownership.

My rough draft plan would be to 

1. Update plugins to the latest version of backstage
2. Resolve any outstanding Issues
3. Migrate plugins
4. Redirect feature requests to `backstage/community-plugins`

Thoughts and comments? 

---

## Update - December 6, 2024

The workspace has been created, and the search module has been migrated. Plugins will not be marked as deprecated in the `procore-oss` org until **ALL** plugins are migrated.

- [x] [PR](https://github.com/backstage/community-plugins/pull/2399) @procore-oss/backstage-plugin-announcements-backend
- [x] [PR](https://github.com/backstage/community-plugins/pull/2154) @procore-oss/backstage-plugin-announcements-common
- [x] [PR](https://github.com/backstage/community-plugins/pull/2347) @procore-oss/backstage-plugin-announcements-node
- [x] [PR](https://github.com/backstage/community-plugins/pull/2393) @procore-oss/backstage-plugin-announcements
- [x] [PR](https://github.com/backstage/community-plugins/pull/2148) @procore-oss/backstage-plugin-search-backend-module-announcements
- [x] [PR](https://github.com/backstage/community-plugins/pull/2404) @procore-oss/backstage-plugin-announcements-react

## Update - December 17, 2024

We have decided we will not create a changeset until all plugins are migrated.

* The announcements workspace has been created in the community plugins repo
* The search module was been migrated in https://github.com/backstage/community-plugins/pull/2148

## Update - December 27, 2024

* all plugins have been migrated
* see https://github.com/backstage/community-plugins/commit/dae0126bf7356c19c9bd696020a35b900babbfd8 for information on the first release under the community namespace.

**Comment by kurtaking** [comment]
@gaelgoth wanted to make sure you saw this as you come to mind when I think of additional maintainers.

**Comment by kurtaking** [comment]
I've started this process here - https://github.com/backstage/community-plugins/pull/879

**Comment by awanlin** [comment]
Hi @kurtaking, I saw that the PR you submitted is closed, is the plan to move this still?

**Comment by kurtaking** [comment]
> Hi @kurtaking, I saw that the PR you submitted is closed, is the plan to move this still?

hey @awanlin, yes, that is the plan, but I have struggled to find the time to do so.

**Comment by awanlin** [comment]
Thanks for the update @kurtaking, just wasn't sure if plans had changed once I saw the PR was closed. 👍

**Comment by kurtaking** [comment]
> Thanks for the update @kurtaking, just wasn't sure if plans had changed once I saw the PR was closed. 👍

First-time father with a 3-month-old is taking up all of my free time. 😄 On the flip side, that's also why I need to get it done. So others aren't affected by my absence.

**Comment by kurtaking** [comment]
[Here is the new PR for migration.](https://github.com/backstage/community-plugins/pull/1134)

**Comment by matdtr** [comment]
Hi, 

I saw https://github.com/backstage/community-plugins/pull/1637, it went stale does the migration is still on hold? Or PR should be reopened by backstage maintainers?

**Comment by awanlin** [comment]
I'm happy to reopen it, odd that it never got assigned to anyone when it was created. The challenge is two fold:

1. On our side - Community Plugin Maintainers - this is a massive PR of 150 files to review, as there won't be proper ownership for it, meaning it wall fall to use to review all changes, we need to make sure everything follows the proper conventions.
2. On the Procore side we need someone to help follow up on comments.

**Comment by kurtaking** [comment]
> I'm happy to reopen it, odd that it never got assigned to anyone when it was created. The challenge is two fold:
> 
>     1. On our side - Community Plugin Maintainers - this is a massive PR of 150 files to review, as there won't be proper ownership for it, meaning it wall fall to use to review all changes, we need to make sure everything follows the proper conventions.
> 
>     2. On the Procore side we need someone to help follow up on comments.

I continue to struggle to find time to take care of this. I agree the PR gets too large too quickly. I was thinking maybe we move one at a time?

**Comment by kurtaking** [comment]
https://github.com/procore-oss/backstage-plugin-announcements/pull/541 deprecates the plugins under the `@procore-oss` namespace and is the final PR as part of the migration effort.
