### ISSUE TITLE
🚀 Feature: Possibility to activate/deactivate announcements

### ISSUE THREAD

**Issue by PedroAlmondo** [procore-oss/backstage-plugin-announcements#379]
### 🔖 Feature description

Adding ability to make announcements active (default) and inactive - inactive announcements don't appear as banners and in other 'notification' ways, but can still be seen in history and possibly activated (then banners show again). 

### 🎤 Context

Sometimes we would like to make an announcement - f.e. about some issue we have, downtime, features not working or maybe f.e events that are currently going on, but these announcements related to something that is happening in a very specific time range will persist for the users if not deleted, which can be very misleading, like we fixed our feature, but the announcement about it is still visible and deleting it is also not the best option - we would like to have it in history. It would be very useful to just have a possibility to make the announcement 'inactive'.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kurtaking** [comment]
Hey @PedroAlmondo, check out https://github.com/procore-oss/backstage-plugin-announcements/issues/301 as the two issues are very similar.

**Comment by kurtaking** [comment]
I started looking at this and ran into one pretty big issue - where do we _activate_ and _deactivate_ them!? Well, that led to the release of a dedicated [admin portal to manage announcements](https://github.com/procore-oss/backstage-plugin-announcements/pull/461). 

Next, we can update or create a new end user view that filters to only show active announcements by default.
