### ISSUE TITLE
🐛 Bug Report: Render HTML `<img>` tags in announcement posts

### ISSUE THREAD

**Issue by jvanalstyne-mdsol** [procore-oss/backstage-plugin-announcements#393]
### 📜 Description

HTML `<img>` tags do not seem to render in announcement posts, despite being rendered in the editor preview.

### 👍 Expected behavior

HTML `<img>` tags should be rendered accordingly in announcement posts.

Example (from editor preview):
![Screenshot 2024-08-19 at 11 08 44](https://github.com/user-attachments/assets/3330b8ca-63d5-4e32-a09a-3b8f790e1d04)

### 👎 Actual Behavior with Screenshots

The announcement posts show the tags in text.

Example:
<img width="546" alt="Screenshot 2024-08-19 at 8 39 59" src="https://github.com/user-attachments/assets/3c5cca38-496d-47bf-b3d8-0a392a0caa82">

### 👟 Reproduction steps

1. Create a new announcement
2. Include an `<img>` tag with a working `src` url in the body
3. Observe that the image renders as expected in the preview
4. Submit the post
5. Navigate to the newly created announcement post
6. Observe that the images are not rendering, instead showing the tags in text 

### 📃 Provide the context for the Bug.

The `img src` urls appear to be correct since they render in the preview and work elsewhere in our backstage deployment. We are using the provided components from the announcements plugin.

### 🖥️ Your Environment

Backstage v1.29.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
@jvanalstyne-mdsol, are you still willing to submit a PR?

**Comment by jvanalstyne-mdsol** [comment]
Hi @kurtaking - Sorry for not picking this up sooner. I can find some time to work on this but it may be somewhat slow-going due to other priorities.

With the ongoing transfer to the community plugins repo, would it be best to wait to open the PR after that is completed?

**Comment by jvanalstyne-mdsol** [comment]
Sorry for the noise

**Comment by kurtaking** [comment]
fantastic news, thanks @jvanalstyne-mdsol!
