### ISSUE TITLE
🐛 Bug Report: releases are failing

### ISSUE THREAD

**Issue by stephenglass** [procore-oss/backstage-plugin-announcements#401]
### 📜 Description

The last two releases have not published to npm and the release action has been failing. Latest release is at 0.9.2 while npm latest is 0.9.0.

### 👍 Expected behavior

Releases publish to npm

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/f58ba9bc-ef67-4f84-b53b-818973e1b2e3)

![image](https://github.com/user-attachments/assets/a2122680-5676-4772-83b8-b52aed9e7b8e)

### 👟 Reproduction steps

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by kurtaking** [comment]
Thanks for reporting @stephenglass. Should be fixed now.

![image](https://github.com/user-attachments/assets/4c8b8a1e-a182-4bae-abab-fdda51db7308)

**Comment by stephenglass** [comment]
Perfect thank you very much appreciated!
