### ISSUE TITLE
Inability to Hide Three Dots Menu in Announcements Page When No Edit or Delete Permissions

### ISSUE THREAD

**Issue by belurepavan71** [procore-oss/backstage-plugin-announcements#422]
### 📜 Description

The AnnouncementsPage component in the backstage-plugin-announcements plugin always displays the three dots (menu) option. This behavior is implemented in AnnouncementsPage.tsx, around line 161. There is no current way to hide this menu based on user permissions.

**Problem:** 
The menu is visible regardless of user permissions. This can be problematic in cases where the user does not have permissions to edit or delete announcements, as the menu still appears.

References:

[Link to AnnouncementsPage.tsx file](https://github.com/procore-oss/backstage-plugin-announcements/blob/ccdcb29f9a46efbefa83b5d7e13ce73e8ccb8a7a/plugins/announcements/src/components/AnnouncementsPage/AnnouncementsPage.tsx#L161)

### 👍 Expected behavior

The three dots menu should be hidden if the user does not have permissions to edit or delete announcements. This would make the component more intuitive and cleaner in scenarios where the menu options are not relevant to the user.

### 👎 Actual Behavior with Screenshots

<img width="1288" alt="Screenshot 2024-09-19 at 6 51 40 PM" src="https://github.com/user-attachments/assets/e233230e-57a2-4953-9506-fa62de51382d">

### 👟 Reproduction steps

Steps to Reproduce:

- Navigate to the AnnouncementsPage.tsx file in the source code.
- Locate the code around line 161 where the menu is implemented.
- Observe that the menu is always visible and cannot be hidden through configuration or styling.

### 📃 Provide the context for the Bug.

**Suggested Solution:**

 To address the issue of hiding the three dots menu, consider implementing a conditional rendering approach. 
For example:

`{canUpdate && canDelete && <Menu ... />}`
&
`{canUpdate && canDelete && <IconButton ... />}`

This code snippet ensures that the menu is only displayed when both canUpdate and canDelete conditions are true. Alternatively, if the menu should be entirely hidden, implementing a configuration option or prop that allows for toggling its visibility based on user needs would be ideal.

Additional Context: Attempts to customize or hide the menu through existing configuration options have not been successful. A more flexible solution is required to adapt the component to different user scenarios.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am will to submit a PR!

**Comment by kurtaking** [comment]
thank you for your contribution @belurepavan71 !
