### ISSUE TITLE
🐛 Bug Report: The displayed announcement is incorrect.

### ISSUE THREAD

**Issue by drapalaa** [procore-oss/backstage-plugin-announcements#539]
### 📜 Description

The bug occurs when the user is on a particular announcement page and then tries to access another announcement from the search dialogue in the sidebar.

### 👍 Expected behavior

The second announcement should be rendered.

### 👎 Actual Behavior with Screenshots

The URL changes to include the ID of the second announcement, but the first one is still visible on the page.

### 👟 Reproduction steps

Prerequisites: 
1. There is a search button in the sidebar. Clicking on it allows users to search in the dialogue box.
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/ee04c6ab-8b9e-4a0e-a611-b42dcc0e13b3" />

Steps to reproduce:
1. Go to any announcement page.
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/0c44ed96-8bf8-45b3-8743-1c5d49b67a82" />
2. Open the search dialogue, and click on another announcement.
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/8afa05ed-9f35-4b66-a495-96e96c8b2b59" />
3. The ID of the selected announcement is in the URL, but the first announcement is still visible on the page.
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/e56217c5-7f14-41f0-aaf4-7895204a8399" />

### 📃 Provide the context for the Bug.

It seems to me that adding an announcement ID to the `useAsync` dependency array in the `AnnouncementPage` component, might solve this problem. Now the component only fetches the announcement once and not when the ID changes.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kurtaking** [comment]
Hey @drapalaa - this is a great catch and it would be a good contribution. We have migrated the plugins to the community [repo](https://github.com/backstage/community-plugins/tree/main/workspaces/announcements) as of today. 

Are you willing to open the contribution PR there?

**Comment by kurtaking** [comment]
I have opened a copy of this issue in the community repo. Please refer to https://github.com/backstage/community-plugins/issues/2413
