### ISSUE TITLE
🐛 Bug Report: Database does not return the correct count of announcements when using max or offset filter

### ISSUE THREAD

**Issue by kurtaking** [procore-oss/backstage-plugin-announcements#88]
### 📜 Description

I did not get the expected behavior when unit testing the announcements database.  The following unit test adds two entries to the database and then queries with the `max` set to 1. I would expect the count to come back as 1, but it comes back as 2. 

```ts
it('max', async () => {
  await store.insertAnnouncement({
    id: 'id',
    publisher: 'publisher',
    title: 'title',
    excerpt: 'excerpt',
    body: 'body',
    created_at: DateTime.fromISO('2023-10-26T15:28:08.539Z'),
  });

  await store.insertAnnouncement({
    id: 'id2',
    publisher: 'publisher2',
    title: 'title2',
    excerpt: 'excerpt2',
    body: 'body2',
    created_at: DateTime.fromISO('2023-10-26T15:28:08.539Z'),
  });

  const announcements = await store.announcements({
    max: 1,
  });

  expect(announcements).toEqual({
    count: 1,
    results: [
      {
        id: 'id2',
        publisher: 'publisher2',
        title: 'title2',
        excerpt: 'excerpt2',
        body: 'body2',
        category: undefined,
        created_at: timestampToDateTime('2023-10-26T15:28:08.539Z'),
      },
    ],
  });
```

### 👍 Expected behavior

Using `store.announcements({ max: 1 })` should return the correct count. This is likely affecting the `offset` parameter as well.

### 👎 Actual Behavior with Screenshots

I received 1 announcement back, but the count is set to 2

<img width="721" alt="image" src="https://github.com/procore-oss/backstage-plugin-announcements/assets/14222009/0e067c80-1458-4234-91f7-2809700592d7">
<img width="729" alt="image" src="https://github.com/procore-oss/backstage-plugin-announcements/assets/14222009/ea7cf44c-a2ef-4b79-90dd-46105d716e16">

### 👟 Reproduction steps

1. Remove `skip` option on unit tests in `AnnouncementsDatabase.test.ts` found [here](https://github.com/procore-oss/backstage-plugin-announcements/blob/bce49e0a0b24aef851bec6dce48e30b1c689aa45/plugins/announcements-backend/src/service/persistence/AnnouncementsDatabase.test.ts#L281).
2. Run the test suite (`yarn test AnnouncementsDatabase.test.ts`)
3. Observe the behavior. It may be helpful to add a console statement to print the `count` in `AnnouncementsDatabase.ts` and to print the returned announcements within the test.

### 📃 Provide the context for the Bug.

I do not have experience using this feature, but it may affect others

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by wss-alubic** [comment]
@kurtaking I can't reproduce the test failure.  Removing the skips makes the tests pass on a freshly cloned repo:

![image](https://github.com/procore-oss/backstage-plugin-announcements/assets/158481638/95f605d9-23e7-4994-a406-179f2d7439bb)
